version: '3.8'

services:
  telegram-crm:
    build: .
    ports:
      - "8001:8001"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=sqlite:///./bot_database.db
      - HOST=0.0.0.0
      - PORT=8001
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
